server:
  port: 5502
  
spring:
  application:
    name: service-stream-sender
  rabbitmq:
    host: 192.168.134.134
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output: #通道名
          destination: order  #目的地
          content-type: text/plain
          group: default
          