server:
  port: 5501
  
spring:
  application:
    name: service-stream-receiver
  rabbitmq:
    host: 192.168.134.134
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit  #默认的绑定器
      bindings:
        input: #通道名
#          binder: rabbit  #通道绑定的Binder
          destination: order  #目的地
#          content-type: text/plain
          content-type: application/json  #消息格式
          group: default  #消费组名，添加group后队列就是持久化的了
          