server:
  port: 3003
  
spring:
  application:
    name: spring-boot-admin-server
  #启用的环境配置
  profiles:
    active:
    - secure

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #
    lease-renewal-interval-in-seconds: 10  #表示eureka client发送心跳给server端的频率
    health-check-url-path: /actuator/health  #健康检查页面的URL路径
    #注册给eureka时告诉eureka自己的密码
    metadata-map: 
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registry-fetch-interval-seconds: 5  #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    #注册中心地址
    service-url:
      defaultZone: http://root:123456@${eureka.instance.hostname}:3001/eureka/

#管理端点的配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback.xml
  
#每个环境的配置根据 '---'分隔符隔开      
---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  #登录admin server需要的用户名和密码
  security:
    user:
      name: admin
      password: 123456
