server:
  port: 3007

eureka:
  instance: 
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:123456@${eureka.instance.hostname}:3001/eureka/
  
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - name: Hystrix
          args:
            name: hystrixCommand
            fallbackUri: forward:/hystrixCommandFallback
#        - name: Custom1
#          args:
#            message: message value
      routes:
        - id: auth-service
          predicates:
            - Path=/auth-service/**
          uri: lb://auth-service
          filters:
            - StripPrefix=1
        - id: a
          uri: lb://service-consumer-1   #负载均衡
          predicates:
            - Path=/cjm/**
          filters:
            - StripPrefix=1
            - name: Hystrix  #熔断器过滤器
              args:
                name: hystrixCommand  #熔断器名
                fallbackUri: forward:/hystrixCommandFallback  #回退方法
            - name: Custom1
              args:
                message: message value
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddressKeyResolver}"  #限流的键解析器的Bean名
                redis-rate-limiter.replenishRate: 1  #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 5  #令牌桶容量

  #redis
  redis:
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
    host: 192.168.134.134
    port: 7001
#    sentinel:
#      master: mymaster
#      nodes: 192.168.134.134:26379,192.168.134.134:26380

logging:
  config: config/logback.xml
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.boot.autoconfigure: WARN
    