server:
  port: 2001

eureka:
  instance: 
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:123456@${eureka.instance.hostname}:7001/eureka/
  
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - name: Hystrix
          args:
            name: hystrixCommand
            fallbackUri: forward:/hystrixCommandFallback
#        - name: Custom1
#          args:
#            message: message value
      routes:
        - id: auth-service
          predicates:
            - Path=/auth-service/**
          uri: lb://auth-service
          filters:
            - StripPrefix=1
        - id: a
#          uri: http://localhost:9001
          uri: lb://service-consumer-1   #负载均衡
          predicates:
            - Path=/cjm/**
          filters:
            - StripPrefix=1
            - name: Hystrix  #熔断器过滤器
              args:
                name: hystrixCommand  #熔断器名
                fallbackUri: forward:/hystrixCommandFallback  #回退方法
            - name: Custom1
              args:
                message: message value

  #redis
  redis:
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
    sentinel:
      master: mymaster
      nodes: 192.168.134.134:26379,192.168.134.134:26380

logging:
  level:
    org.springframework.cloud.gateway: debug
