server:
  port: 2001
  
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
#          lowerCaseServiceId: true
      routes:
        - id: a
#          uri: http://localhost:9001
#          uri: lb://SERVICE-CONSUMER-1
          uri: lb://service-consumer-1
          predicates:
            - Path=/cjm/**
          filters:
            - StripPrefix=1

eureka:
  instance: 
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:123456@${eureka.instance.hostname}:7001/eureka/
      
logging:
  level:
    org.springframework.cloud.gateway: debug
